import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  viewport: 'initial-scale=1, width=device-width',
  description: 'Generated by create next app',
};

export default function WebLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <h1>web layout</h1>{children}
    </div >
  );
}
