import type { Metadata } from 'next';
import ThemeRegistry from './_components/ThemeRegistry/ThemeRegistry';
import ReactQueryProvider from './_helpers/query/provider';
import { AlertMsg } from './_components/AlertMsg';
import "./globals.css";

export const metadata: Metadata = {
  title: 'Create Next App',
  viewport: 'initial-scale=1, width=device-width',
  description: 'Generated by create next app',
};

export default function GlobalLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ReactQueryProvider>
      <html lang="en">
        <body>
          <ThemeRegistry>
            <AlertMsg />
            {children}
          </ThemeRegistry>
        </body>
      </html >
    </ReactQueryProvider>
  );
}
