'use client'
import type { Metadata } from "next";
import ThemeRegistry from "./_components/ThemeRegistry/ThemeRegistry";
import ReactQueryProvider from "./_helpers/query/provider";
import { AlertMsg } from "./_components/AlertMsg";
import "./globals.css";
import NextTopLoader from 'nextjs-toploader';

export const metadata: Metadata = {
  title: "Create Next App",
  viewport: "initial-scale=1, width=device-width",
  description: "Generated by create next app",
};

export default function GlobalLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ReactQueryProvider>
      <html lang="en">
        <body>
          <ThemeRegistry>
            <AlertMsg />
            <NextTopLoader
  color="#2299DD"
  initialPosition={0.08}
  crawlSpeed={200}
  height={3}
  crawl={true}
  showSpinner={true}
  easing="ease"
  speed={200}
  shadow="0 0 10px #2299DD,0 0 5px #2299DD"
/>                        {children}
          </ThemeRegistry>
        </body>
      </html>
    </ReactQueryProvider>
  );
}
